# Generated by Django 5.2.2 on 2025-06-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="chess_openings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("by_white", models.CharField(max_length=50)),
                ("by_black", models.CharField(max_length=50)),
            ],
        ),
    ]
