# Generated by Django 5.2.2 on 2025-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chess_openings",
            name="by_black",
        ),
        migrations.RemoveField(
            model_name="chess_openings",
            name="by_white",
        ),
        migrations.AddField(
            model_name="chess_openings",
            name="first_move_by_black",
            field=models.CharField(default="e4", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chess_openings",
            name="first_move_by_white",
            field=models.CharField(default="e5", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chess_openings",
            name="opening_name",
            field=models.CharField(
                default="cannot say anything , play more moves", max_length=50
            ),
            preserve_default=False,
        ),
    ]
