# Generated by Django 5.2.2 on 2025-06-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="content",
            field=models.TextField(default="Python is awesome"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title",
            field=models.CharField(default="First blog", max_length=100),
            preserve_default=False,
        ),
    ]
