# Generated by Django 5.2.2 on 2025-06-10 09:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("220bbec0-fbfe-4982-af14-c8a5f298bb06"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
