# Generated by Django 5.2.2 on 2025-06-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blogpost_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
